#!/usr/bin/env bash
# ./agent — entry point for the 0-to-1 Agent Skills CLI.
# Generated by install.sh. Do not edit manually.
#
# Resolves project root by walking up to .briefcase/ sentinel,
# selects the best Python interpreter, and bootstraps the CLI.

set -euo pipefail

# --- Find project root by walking up to .briefcase/ sentinel ---
find_project_root() {
    local dir
    dir="$(cd "${1:-.}" && pwd)"
    while true; do
        if [ -d "$dir/.briefcase" ]; then
            echo "$dir"
            return 0
        fi
        local parent
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            return 1
        fi
        dir="$parent"
    done
}

PROJECT_ROOT="$(find_project_root "$(pwd)")" || {
    echo "Error: not inside an initialized project." >&2
    echo "No .briefcase/ directory found. Run install.sh first." >&2
    exit 1
}

# --- Select Python interpreter ---
# Preference: .briefcase/.venv > system python3
if [ -x "$PROJECT_ROOT/.briefcase/.venv/bin/python" ]; then
    PYTHON="$PROJECT_ROOT/.briefcase/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="python3"
else
    echo "Error: Python 3 not found." >&2
    echo "Install Python 3 or create .briefcase/.venv/." >&2
    exit 1
fi

# --- Bootstrap and run CLI ---
# Insert .briefcase/ at front of sys.path so 'from src.*' resolves
# to .briefcase/src/ per the sys.path contract (D-032).
exec "$PYTHON" -c "
import sys, os
sys.path.insert(0, os.path.join('$PROJECT_ROOT', '.briefcase'))
from src.cli.main import cli
cli()
" "$@"
