#!/usr/bin/env bash
# install.sh — Install the 0-to-1 Agent Skills framework into a consumer project.
#
# Usage:
#   ./install.sh                     # Install from local repo clone
#   curl <url> | bash                # Streamed install (future)
#
# What this does:
#   1. Copies src/, skills/, template/ into .briefcase/
#   2. Generates ./agent entry point at project root
#   3. Creates .briefcase/storage.yaml (backend: local) if not present
#   4. Appends framework entries to .gitignore (idempotent)
#   5. Creates .skills symlink for native skill discovery
#   6. Reports Notion token status
#
# Idempotent: re-running overwrites .briefcase/ and ./agent only.
# Never modifies consumer src/, tests/, docs/, or any other consumer-owned file.

set -euo pipefail

# --- Resolve framework source directory ---
# When run from a local clone, SCRIPT_DIR is the framework repo root.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Allow override via FRAMEWORK_DIR for testing
FRAMEWORK_DIR="${FRAMEWORK_DIR:-$SCRIPT_DIR}"

# Allow override via TARGET_DIR for testing; default to current directory
TARGET_DIR="${TARGET_DIR:-$(pwd)}"

# --- Validate framework source ---
for required_dir in src skills template; do
    if [ ! -d "$FRAMEWORK_DIR/$required_dir" ]; then
        echo "Error: $FRAMEWORK_DIR/$required_dir not found." >&2
        echo "Run install.sh from the framework repo root, or set FRAMEWORK_DIR." >&2
        exit 1
    fi
done

BRIEFCASE="$TARGET_DIR/.briefcase"

echo "Installing 0-to-1 Agent Skills framework..."
echo "  Source:  $FRAMEWORK_DIR"
echo "  Target:  $TARGET_DIR"
echo ""

# --- 1. Copy framework code into .briefcase/ ---
echo "  [1/4] Copying framework to .briefcase/..."

# Remove old copy for clean overwrite
if [ -d "$BRIEFCASE" ]; then
    rm -rf "$BRIEFCASE/src" "$BRIEFCASE/skills" "$BRIEFCASE/template"
fi
mkdir -p "$BRIEFCASE"

cp -r "$FRAMEWORK_DIR/src"      "$BRIEFCASE/src"
cp -r "$FRAMEWORK_DIR/skills"   "$BRIEFCASE/skills"
cp -r "$FRAMEWORK_DIR/template" "$BRIEFCASE/template"

# Rewrite skill path references from skills/ to .briefcase/skills/
find "$BRIEFCASE/skills" -name '*.md' -exec sed -i '' 's|skills/|.briefcase/skills/|g' {} + 2>/dev/null || \
find "$BRIEFCASE/skills" -name '*.md' -exec sed -i 's|skills/|.briefcase/skills/|g' {} +

echo "        src/, skills/, template/ copied."

# --- 2. Create .briefcase/storage.yaml (if not present) ---
STORAGE_YAML="$BRIEFCASE/storage.yaml"
if [ ! -f "$STORAGE_YAML" ]; then
    echo "  [2/4] Creating .briefcase/storage.yaml (backend: local)..."
    cat > "$STORAGE_YAML" << 'EOF'
backend: local
EOF
    echo "        Default backend: local."
else
    echo "  [2/4] .briefcase/storage.yaml already exists — skipped."
fi

# --- 3. Generate ./agent entry point ---
echo "  [3/4] Generating ./agent entry point..."
AGENT_WRAPPER="$TARGET_DIR/agent"

cat > "$AGENT_WRAPPER" << 'WRAPPER_EOF'
#!/usr/bin/env bash
# ./agent — entry point for the 0-to-1 Agent Skills CLI.
# Generated by install.sh. Do not edit manually.

set -euo pipefail

find_project_root() {
    local dir
    dir="$(cd "${1:-.}" && pwd)"
    while true; do
        if [ -d "$dir/.briefcase" ]; then
            echo "$dir"
            return 0
        fi
        local parent
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            return 1
        fi
        dir="$parent"
    done
}

PROJECT_ROOT="$(find_project_root "$(pwd)")" || {
    echo "Error: not inside an initialized project." >&2
    echo "No .briefcase/ directory found. Run install.sh first." >&2
    exit 1
}

if [ -x "$PROJECT_ROOT/.briefcase/.venv/bin/python" ]; then
    PYTHON="$PROJECT_ROOT/.briefcase/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="python3"
else
    echo "Error: Python 3 not found." >&2
    exit 1
fi

exec "$PYTHON" -c "
import sys, os
sys.path.insert(0, os.path.join('$PROJECT_ROOT', '.briefcase'))
from src.cli.main import cli
cli()
" "$@"
WRAPPER_EOF

chmod +x "$AGENT_WRAPPER"
echo "        ./agent created and made executable."

# --- 4. Update .gitignore (idempotent) ---
echo "  [4/5] Updating .gitignore..."

# Prefer the shared Python helper (single source of truth for entries).
# Fall back to bash if python3 is unavailable.
_gitignore_bash_fallback() {
    local gi="$TARGET_DIR/.gitignore"
    touch "$gi"
    # Mirror BASELINE_ENTRIES from src/core/gitignore.py
    for entry in ".briefcase/" ".env"; do
        if ! grep -qF "$entry" "$gi"; then
            printf '\n# Managed by 0-to-1 Agent Skills\n%s\n' "$entry" >> "$gi"
        fi
    done
}

if command -v python3 >/dev/null 2>&1; then
    TARGET_DIR="$TARGET_DIR" PYTHONPATH="$BRIEFCASE" python3 -c "
import os
from src.core.gitignore import ensure_gitignore, BASELINE_ENTRIES
ensure_gitignore(os.environ['TARGET_DIR'], BASELINE_ENTRIES)
" 2>/dev/null || {
        echo "        ⚠ Python helper failed; using bash fallback."
        _gitignore_bash_fallback
    }
else
    _gitignore_bash_fallback
fi

echo "        .gitignore updated."

# --- 5. Native skill discovery (optional) ---
# Expose skill files through a well-known path so AI coding tools can
# discover them automatically.  Creates a minimal .skills/ directory with
# symlinks back to .briefcase/skills/ so there is one source of truth.
echo "  [5/5] Setting up skill discovery..."
SKILLS_LINK="$TARGET_DIR/.skills"
if [ ! -e "$SKILLS_LINK" ]; then
    ln -s .briefcase/skills "$SKILLS_LINK" 2>/dev/null && \
        echo "        .skills -> .briefcase/skills/ symlink created." || \
        echo "        ⚠ Could not create .skills symlink (non-fatal)."
else
    echo "        .skills already exists — skipped."
fi

# --- Summary ---
echo ""
echo "Done! Framework installed to .briefcase/"
echo ""
echo "  Created:"
echo "    .briefcase/src/       — CLI and storage backends"
echo "    .briefcase/skills/    — Agent role definitions"
echo "    .briefcase/template/  — Document templates"
echo "    .briefcase/storage.yaml — Storage config (backend: local)"
echo "    .skills               — Symlink for native skill discovery"
echo "    ./agent               — CLI entry point"
echo ""

# --- Notion token check ---
if [ -n "${NOTION_API_KEY:-}" ]; then
    echo "  Notion: NOTION_API_KEY detected. Ready for Notion-backed commands."
    echo "          Run './agent setup' to provision a Notion workspace."
elif [ -n "${NOTION_API_TOKEN:-}" ]; then
    echo "  Notion: Legacy NOTION_API_TOKEN detected."
    echo "          Rename to NOTION_API_KEY for forward compatibility."
else
    echo "  Notion: No API key detected."
    echo "          To use Notion backend, set NOTION_API_KEY in your environment."
fi

echo ""
echo "Next steps:"
echo "  ./agent --help          — See available commands"
echo "  ./agent setup           — Initialize storage backend"
echo "  ./agent inbox list      — List inbox ideas"
