#!/usr/bin/env bash
# install.sh — Install the 0-to-1 Agent Skills framework into a consumer project.
#
# Usage:
#   ./install.sh                     # Install from local repo clone
#   curl <url> | bash                # Streamed install (future)
#
# What this does:
#   1. Copies src/, skills/, template/ into .briefcase/
#   2. Creates .briefcase/storage.yaml (backend: local) if not present
#   3. Generates ./agent entry point at project root
#   4. Creates Python venv and installs dependencies
#   5. Creates docs/plan/ directory structure for local backend
#   6. Copies AGENTS.md, CLAUDE.md, and _project/ templates
#   7. Appends framework entries to .gitignore (idempotent)
#   8. Creates .skills symlink for native skill discovery
#   9. Reports Notion token status
#
# Idempotent: re-running overwrites .briefcase/ and ./agent only.
# Never modifies consumer src/, tests/, docs/, or any other consumer-owned file.

set -euo pipefail

# --- Resolve framework source directory ---
# When run from a local clone, SCRIPT_DIR is the framework repo root.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Allow override via FRAMEWORK_DIR for testing
FRAMEWORK_DIR="${FRAMEWORK_DIR:-$SCRIPT_DIR}"

# Allow override via TARGET_DIR for testing; default to current directory
TARGET_DIR="${TARGET_DIR:-$(pwd)}"

# --- Validate framework source ---
for required_dir in src skills template; do
    if [ ! -d "$FRAMEWORK_DIR/$required_dir" ]; then
        echo "Error: $FRAMEWORK_DIR/$required_dir not found." >&2
        echo "Run install.sh from the framework repo root, or set FRAMEWORK_DIR." >&2
        exit 1
    fi
done

BRIEFCASE="$TARGET_DIR/.briefcase"

echo "Installing 0-to-1 Agent Skills framework..."
echo "  Source:  $FRAMEWORK_DIR"
echo "  Target:  $TARGET_DIR"
echo ""

TOTAL_STEPS=8

# --- 1. Copy framework code into .briefcase/ ---
echo "  [1/$TOTAL_STEPS] Copying framework to .briefcase/..."

# Remove old copy for clean overwrite
if [ -d "$BRIEFCASE" ]; then
    rm -rf "$BRIEFCASE/src" "$BRIEFCASE/skills" "$BRIEFCASE/template"
fi
mkdir -p "$BRIEFCASE"

cp -r "$FRAMEWORK_DIR/src"      "$BRIEFCASE/src"
cp -r "$FRAMEWORK_DIR/skills"   "$BRIEFCASE/skills"
cp -r "$FRAMEWORK_DIR/template" "$BRIEFCASE/template"

# Copy pyproject.toml for dependency management
if [ -f "$FRAMEWORK_DIR/pyproject.toml" ]; then
    cp "$FRAMEWORK_DIR/pyproject.toml" "$BRIEFCASE/pyproject.toml"
fi

# Rewrite skill path references from skills/ to .briefcase/skills/
find "$BRIEFCASE/skills" -name '*.md' -exec sed -i '' 's|skills/|.briefcase/skills/|g' {} + 2>/dev/null || \
find "$BRIEFCASE/skills" -name '*.md' -exec sed -i 's|skills/|.briefcase/skills/|g' {} +

echo "        src/, skills/, template/ copied."

# --- 2. Create .briefcase/storage.yaml (if not present) ---
STORAGE_YAML="$BRIEFCASE/storage.yaml"
if [ ! -f "$STORAGE_YAML" ]; then
    echo "  [2/$TOTAL_STEPS] Creating .briefcase/storage.yaml (backend: local)..."
    cat > "$STORAGE_YAML" << 'EOF'
backend: local
EOF
    echo "        Default backend: local."
else
    echo "  [2/$TOTAL_STEPS] .briefcase/storage.yaml already exists — skipped."
fi

# --- 3. Generate ./agent entry point ---
echo "  [3/$TOTAL_STEPS] Generating ./agent entry point..."
AGENT_WRAPPER="$TARGET_DIR/agent"

cat > "$AGENT_WRAPPER" << 'WRAPPER_EOF'
#!/usr/bin/env bash
# ./agent — entry point for the 0-to-1 Agent Skills CLI.
# Generated by install.sh. Do not edit manually.

set -euo pipefail

find_project_root() {
    local dir
    dir="$(cd "${1:-.}" && pwd)"
    while true; do
        if [ -d "$dir/.briefcase" ]; then
            echo "$dir"
            return 0
        fi
        local parent
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            return 1
        fi
        dir="$parent"
    done
}

PROJECT_ROOT="$(find_project_root "$(pwd)")" || {
    echo "Error: not inside an initialized project." >&2
    echo "No .briefcase/ directory found. Run install.sh first." >&2
    exit 1
}

if [ -x "$PROJECT_ROOT/.briefcase/.venv/bin/python" ]; then
    PYTHON="$PROJECT_ROOT/.briefcase/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="python3"
else
    echo "Error: Python 3 not found." >&2
    exit 1
fi

exec "$PYTHON" -c "
import sys, os
sys.path.insert(0, os.path.join('$PROJECT_ROOT', '.briefcase'))
from src.cli.main import cli
cli()
" "$@"
WRAPPER_EOF

chmod +x "$AGENT_WRAPPER"
echo "        ./agent created and made executable."

# --- 4. Create Python venv and install dependencies ---
echo "  [4/$TOTAL_STEPS] Creating Python venv and installing dependencies..."
if [ ! -d "$BRIEFCASE/.venv" ]; then
    python3 -m venv "$BRIEFCASE/.venv" 2>/dev/null && \
        "$BRIEFCASE/.venv/bin/pip" install -q --upgrade pip 2>/dev/null && \
        "$BRIEFCASE/.venv/bin/pip" install -q -e "$BRIEFCASE/" 2>/dev/null && \
        echo "        .venv created and dependencies installed." || {
            echo "        ⚠ Could not create venv (non-fatal). CLI will use system python3."
        }
else
    echo "        .venv already exists — skipped."
fi

# --- 5. Create docs/plan/ directory structure for local backend ---
echo "  [5/$TOTAL_STEPS] Creating docs/plan/ directory structure..."
mkdir -p "$TARGET_DIR/docs/plan/_shared" "$TARGET_DIR/docs/plan/_reference/adr"
# Copy template files if they don't exist yet (idempotent)
if [ ! -f "$TARGET_DIR/docs/plan/_inbox.md" ] && [ -f "$BRIEFCASE/template/_inbox.md" ]; then
    cp "$BRIEFCASE/template/_inbox.md" "$TARGET_DIR/docs/plan/_inbox.md"
fi
if [ ! -f "$TARGET_DIR/docs/plan/_shared/backlog.md" ] && [ -f "$BRIEFCASE/template/backlog.md" ]; then
    cp "$BRIEFCASE/template/backlog.md" "$TARGET_DIR/docs/plan/_shared/backlog.md"
fi
echo "        docs/plan/ structure ready."

# --- 6. Copy AGENTS.md, CLAUDE.md, and _project/ templates ---
echo "  [6/$TOTAL_STEPS] Copying project entrypoint files..."
# Copy AGENTS.md and CLAUDE.md from the rewritten .briefcase/skills/ PLAYBOOK
# Generate consumer-facing AGENTS.md if not present
if [ ! -f "$TARGET_DIR/AGENTS.md" ]; then
    cat > "$TARGET_DIR/AGENTS.md" << 'AGENTS_EOF'
# AGENTS.md

Read `.briefcase/skills/PLAYBOOK.md` fully before taking any action.

## Commands

| Task | Command |
|------|--------|
| List inbox | `./agent inbox list` |
| Add idea | `./agent inbox add --type idea --text "..."` |
| Read brief | `./agent brief read {name}` |
| List backlog | `./agent backlog list` |
| Setup | `./agent setup` |
AGENTS_EOF
    echo "        AGENTS.md created."
else
    echo "        AGENTS.md already exists — skipped."
fi

if [ ! -f "$TARGET_DIR/CLAUDE.md" ]; then
    cat > "$TARGET_DIR/CLAUDE.md" << 'CLAUDE_EOF'
# CLAUDE.md

This is the Claude Code entrypoint. All workflow rules, agent routing, folder structure,
session protocols, and collaboration guidelines are defined in `AGENTS.md`.

**Read `AGENTS.md` before taking any action.**
CLAUDE_EOF
    echo "        CLAUDE.md created."
else
    echo "        CLAUDE.md already exists — skipped."
fi

# Copy _project/ templates if the directory doesn't exist
if [ ! -d "$TARGET_DIR/_project" ]; then
    mkdir -p "$TARGET_DIR/_project"
    for tpl in definition-of-done.md testing-strategy.md tech-stack.md; do
        if [ -f "$BRIEFCASE/template/$tpl" ]; then
            cp "$BRIEFCASE/template/$tpl" "$TARGET_DIR/_project/$tpl"
        fi
    done
    echo "        _project/ templates copied."
else
    echo "        _project/ already exists — skipped."
fi

# --- 7. Update .gitignore (idempotent) ---
echo "  [7/$TOTAL_STEPS] Updating .gitignore..."

# Prefer the shared Python helper (single source of truth for entries).
# Fall back to bash if python3 is unavailable.
_gitignore_bash_fallback() {
    local gi="$TARGET_DIR/.gitignore"
    touch "$gi"
    # Mirror BASELINE_ENTRIES from src/core/gitignore.py
    for entry in ".briefcase/" ".env"; do
        if ! grep -qF "$entry" "$gi"; then
            printf '\n# Managed by 0-to-1 Agent Skills\n%s\n' "$entry" >> "$gi"
        fi
    done
}

if command -v python3 >/dev/null 2>&1; then
    TARGET_DIR="$TARGET_DIR" PYTHONPATH="$BRIEFCASE" python3 -c "
import os
from src.core.gitignore import ensure_gitignore, BASELINE_ENTRIES
ensure_gitignore(os.environ['TARGET_DIR'], BASELINE_ENTRIES)
" 2>/dev/null || {
        echo "        ⚠ Python helper failed; using bash fallback."
        _gitignore_bash_fallback
    }
else
    _gitignore_bash_fallback
fi

echo "        .gitignore updated."

# --- 5. Native skill discovery (optional) ---
# Expose skill files through a well-known path so AI coding tools can
# discover them automatically.  Creates a minimal .skills/ directory with
# symlinks back to .briefcase/skills/ so there is one source of truth.
echo "  [8/$TOTAL_STEPS] Setting up skill discovery..."
SKILLS_LINK="$TARGET_DIR/.skills"
if [ ! -e "$SKILLS_LINK" ]; then
    ln -s .briefcase/skills "$SKILLS_LINK" 2>/dev/null && \
        echo "        .skills -> .briefcase/skills/ symlink created." || \
        echo "        ⚠ Could not create .skills symlink (non-fatal)."
else
    echo "        .skills already exists — skipped."
fi

# --- Summary ---
echo ""
echo "Done! Framework installed to .briefcase/"
echo ""
echo "  Created:"
echo "    .briefcase/src/       — CLI and storage backends"
echo "    .briefcase/skills/    — Agent role definitions"
echo "    .briefcase/template/  — Document templates"
echo "    .briefcase/storage.yaml — Storage config (backend: local)"
echo "    .briefcase/.venv/     — Python virtual environment with deps"
echo "    .skills               — Symlink for native skill discovery"
echo "    ./agent               — CLI entry point"
echo "    AGENTS.md             — Agent entrypoint"
echo "    CLAUDE.md             — Claude Code entrypoint"
echo "    _project/             — Project constants (tech-stack, DoD, tests)"
echo "    docs/plan/            — Local planning artifacts"
echo ""

# --- Notion token check ---
if [ -n "${NOTION_API_KEY:-}" ]; then
    echo "  Notion: NOTION_API_KEY detected. Ready for Notion-backed commands."
    echo "          Run './agent setup' to provision a Notion workspace."
elif [ -n "${NOTION_API_TOKEN:-}" ]; then
    echo "  Notion: Legacy NOTION_API_TOKEN detected."
    echo "          Rename to NOTION_API_KEY for forward compatibility."
else
    echo "  Notion: No API key detected."
    echo "          To use Notion backend, set NOTION_API_KEY in your environment."
fi

echo ""
echo "Next steps:"
echo "  ./agent --help          — See available commands"
echo "  ./agent setup           — Initialize storage backend (optional)"
echo "  ./agent inbox list      — List inbox ideas"
echo "  ./agent inbox add       — Capture a new idea"
