"""Integration tests for install.sh."""

import os
import subprocess
from pathlib import Path

import pytest


FRAMEWORK_DIR = str(Path(__file__).resolve().parents[3])


@pytest.fixture
def consumer_dir(tmp_path):
    """Create an empty consumer project directory."""
    target = tmp_path / "consumer"
    target.mkdir()
    return target


def run_install(consumer_dir, env_overrides=None):
    """Run install.sh with TARGET_DIR pointing to consumer_dir."""
    env = os.environ.copy()
    env["FRAMEWORK_DIR"] = FRAMEWORK_DIR
    env["TARGET_DIR"] = str(consumer_dir)
    if env_overrides:
        env.update(env_overrides)

    result = subprocess.run(
        ["bash", os.path.join(FRAMEWORK_DIR, "install.sh")],
        capture_output=True, text=True,
        env=env,
        timeout=30,
    )
    return result


class TestFreshInstall:
    def test_creates_briefcase_directory(self, consumer_dir):
        result = run_install(consumer_dir)
        assert result.returncode == 0
        assert (consumer_dir / ".briefcase").is_dir()

    def test_copies_framework_subdirs(self, consumer_dir):
        run_install(consumer_dir)
        assert (consumer_dir / ".briefcase" / "src").is_dir()
        assert (consumer_dir / ".briefcase" / "skills").is_dir()
        assert (consumer_dir / ".briefcase" / "template").is_dir()

    def test_creates_storage_yaml(self, consumer_dir):
        run_install(consumer_dir)
        yaml_path = consumer_dir / ".briefcase" / "storage.yaml"
        assert yaml_path.exists()
        content = yaml_path.read_text()
        assert "backend: local" in content

    def test_generates_briefcase_wrapper(self, consumer_dir):
        run_install(consumer_dir)
        wrapper = consumer_dir / "briefcase"
        assert wrapper.exists()
        assert os.access(wrapper, os.X_OK)
        content = wrapper.read_text()
        assert ".briefcase" in content
        assert "find_project_root" in content

    def test_creates_gitignore_entries(self, consumer_dir):
        run_install(consumer_dir)
        gitignore = consumer_dir / ".gitignore"
        assert gitignore.exists()
        content = gitignore.read_text()
        assert ".briefcase/" in content
        assert ".env" in content

    def test_rewrites_skill_paths(self, consumer_dir):
        run_install(consumer_dir)
        playbook = consumer_dir / ".briefcase" / "skills" / "PLAYBOOK.md"
        if playbook.exists():
            content = playbook.read_text()
            # Should not contain raw .skills/ references
            # (they should be rewritten to .briefcase/skills/)
            # Note: some may remain as part of a path convention explanation
            assert ".briefcase/skills/" in content

    def test_does_not_touch_consumer_dirs(self, consumer_dir):
        """Install must not create consumer-owned directories."""
        (consumer_dir / "src").mkdir()
        (consumer_dir / "src" / "app.py").write_text("# consumer code")

        run_install(consumer_dir)

        # Consumer file should be untouched
        assert (consumer_dir / "src" / "app.py").read_text() == "# consumer code"

    def test_generated_entrypoint_files_include_scaffolding_header(self, consumer_dir):
        run_install(consumer_dir)
        agents = (consumer_dir / "AGENTS.md").read_text()
        claude = (consumer_dir / "CLAUDE.md").read_text()
        assert "Generated by install.sh" in agents
        assert "Generated by install.sh" in claude


class TestIdempotentReInstall:
    def test_does_not_duplicate_gitignore(self, consumer_dir):
        run_install(consumer_dir)
        run_install(consumer_dir)

        content = (consumer_dir / ".gitignore").read_text()
        # Each entry should appear exactly once
        assert content.count(".briefcase/") == 1
        assert content.count(".env") == 1

    def test_preserves_storage_yaml(self, consumer_dir):
        run_install(consumer_dir)

        # Modify storage.yaml to simulate user config
        yaml_path = consumer_dir / ".briefcase" / "storage.yaml"
        yaml_path.write_text("backend: notion\nnotion:\n  parent_page_id: abc\n")

        run_install(consumer_dir)

        # Should not be overwritten
        content = yaml_path.read_text()
        assert "notion" in content
        assert "abc" in content

    def test_overwrites_framework_code(self, consumer_dir):
        run_install(consumer_dir)

        # Add a marker file inside .briefcase/src/ to verify it gets replaced
        marker = consumer_dir / ".briefcase" / "src" / "__marker__.txt"
        marker.write_text("old")

        run_install(consumer_dir)

        # Marker should be gone (fresh copy)
        assert not marker.exists()


class TestBriefcaseWrapperIntegration:
    def test_briefcase_help_works(self, consumer_dir):
        run_install(consumer_dir)

        result = subprocess.run(
            [str(consumer_dir / "briefcase"), "--help"],
            capture_output=True, text=True,
            cwd=str(consumer_dir),
            timeout=15,
        )
        assert result.returncode == 0
        assert "Agent workflow CLI" in result.stdout

    def test_briefcase_command_works_with_local_backend(self, consumer_dir):
        run_install(consumer_dir)

        # Create minimal local backend structure
        plan = consumer_dir / "docs" / "plan"
        shared = plan / "_shared"
        shared.mkdir(parents=True, exist_ok=True)
        (plan / "_inbox.md").write_text("# Inbox\n\n## Entries\n\n")
        (shared / "backlog.md").write_text(
            "# Backlog\n\n"
            "| ID | Type | Use Case | Feature | Title | Priority | Status | Notes |\n"
            "|---|---|---|---|---|---|---|---|\n"
        )
        (consumer_dir / "_project").mkdir(exist_ok=True)

        result = subprocess.run(
            [str(consumer_dir / "briefcase"), "inbox", "list"],
            capture_output=True, text=True,
            cwd=str(consumer_dir),
            timeout=15,
        )
        assert result.returncode == 0
        assert '"success": true' in result.stdout


class TestNotionTokenDetection:
    def test_detects_notion_api_key(self, consumer_dir):
        result = run_install(consumer_dir, {"NOTION_API_KEY": "test-key"})
        assert result.returncode == 0
        assert "NOTION_API_KEY detected" in result.stdout

    def test_detects_legacy_token(self, consumer_dir):
        env = {"NOTION_API_TOKEN": "legacy-key"}
        # Clear NOTION_API_KEY if set in parent env
        env["NOTION_API_KEY"] = ""
        result = run_install(consumer_dir, env)
        assert result.returncode == 0
        assert "Legacy" in result.stdout or "legacy" in result.stdout or "NOTION_API_TOKEN" in result.stdout

    def test_reports_no_token(self, consumer_dir):
        env = {"NOTION_API_KEY": "", "NOTION_API_TOKEN": ""}
        result = run_install(consumer_dir, env)
        assert result.returncode == 0
        assert "No API key" in result.stdout or "NOTION_API_KEY" in result.stdout


class TestConditionalDocsPlan:
    def test_local_backend_creates_docs_plan(self, consumer_dir):
        """Default install (local backend) creates docs/plan/ directory."""
        run_install(consumer_dir)
        assert (consumer_dir / "docs" / "plan" / "_shared").is_dir()
        assert (consumer_dir / "docs" / "plan" / "_reference" / "adr").is_dir()

    def test_notion_backend_skips_docs_plan(self, consumer_dir):
        """When storage.yaml is notion, docs/plan/ should NOT be created."""
        # First install to create .briefcase/
        run_install(consumer_dir)

        # Switch backend to notion
        yaml_path = consumer_dir / ".briefcase" / "storage.yaml"
        yaml_path.write_text("backend: notion\n")

        # Remove docs/plan/ to verify it's not re-created
        docs_plan = consumer_dir / "docs" / "plan"
        if docs_plan.exists():
            import shutil
            shutil.rmtree(docs_plan)

        # Re-install — should skip docs/plan/
        result = run_install(consumer_dir)
        assert result.returncode == 0
        assert not (consumer_dir / "docs" / "plan").exists()
        assert "Skipping docs/plan/" in result.stdout


class TestInstallerHardening:
    def test_pip_uses_python_m_pip(self, consumer_dir):
        """All pip invocations should use .venv/bin/python -m pip."""
        install_sh = Path(FRAMEWORK_DIR) / "install.sh"
        content = install_sh.read_text()
        # Should NOT have direct .venv/bin/pip calls
        assert ".venv/bin/pip" not in content
        # Should have python -m pip
        assert "python\" -m pip" in content or "python -m pip" in content

    def test_no_swallowed_stderr_in_venv_block(self, consumer_dir):
        """venv/pip block should not redirect stderr to /dev/null."""
        install_sh = Path(FRAMEWORK_DIR) / "install.sh"
        content = install_sh.read_text()
        # Find the venv section (step 4)
        venv_section_start = content.find("Create Python venv")
        venv_section_end = content.find("--- 5.", venv_section_start)
        venv_section = content[venv_section_start:venv_section_end]
        assert "2>/dev/null" not in venv_section

    def test_no_agent_command_references_in_messages(self, consumer_dir):
        """Post-install messages should reference './briefcase', not 'agent'."""
        result = run_install(consumer_dir)
        assert result.returncode == 0
        stdout = result.stdout
        # Check that CLI references use ./briefcase
        assert "./briefcase --help" in stdout
        assert "./briefcase setup" in stdout
        # Should not have 'agent' as a CLI command reference (but 'Agent' in
        # descriptions like "Agent workflow CLI" is fine)
        for line in stdout.splitlines():
            lower = line.lower().strip()
            if lower.startswith("./briefcase") or "agent workflow" in lower:
                continue
            # Lines like "  agent sync local" should not exist
            assert "`agent " not in line

    def test_non_interactive_flag_succeeds(self, consumer_dir):
        """--non-interactive should complete successfully."""
        env = os.environ.copy()
        env["FRAMEWORK_DIR"] = FRAMEWORK_DIR
        env["TARGET_DIR"] = str(consumer_dir)

        result = subprocess.run(
            ["bash", os.path.join(FRAMEWORK_DIR, "install.sh"), "--non-interactive"],
            capture_output=True, text=True, env=env, timeout=30,
        )
        assert result.returncode == 0
        assert (consumer_dir / ".briefcase").is_dir()

    def test_non_interactive_env_var(self, consumer_dir):
        """BRIEFCASE_NON_INTERACTIVE=true should work like --non-interactive."""
        result = run_install(consumer_dir, {"BRIEFCASE_NON_INTERACTIVE": "true"})
        assert result.returncode == 0
        assert (consumer_dir / ".briefcase").is_dir()

    def test_interactive_mode_unchanged(self, consumer_dir):
        """Without --non-interactive, install still works normally."""
        result = run_install(consumer_dir)
        assert result.returncode == 0
        assert (consumer_dir / ".briefcase").is_dir()
        assert (consumer_dir / "briefcase").exists()


class TestReinstallBugFixes:
    def test_reinstall_runs_pip_even_when_venv_exists(self, consumer_dir):
        """Bug fix: installer must run pip install even if .venv/ already exists."""
        run_install(consumer_dir)
        # Verify venv exists
        assert (consumer_dir / ".briefcase" / ".venv").is_dir()
        # Re-install should still succeed (pip runs again)
        result = run_install(consumer_dir)
        assert result.returncode == 0
        assert "dependencies installed" in result.stdout

    def test_reinstall_syncs_from_project_storage_yaml(self, consumer_dir):
        """Bug fix: if _project/storage.yaml exists and .briefcase/storage.yaml
        is missing (e.g. after rm -rf .briefcase), installer should copy from
        _project/storage.yaml instead of creating a bare default."""
        run_install(consumer_dir)
        # Simulate user running setup which creates _project/storage.yaml
        project_dir = consumer_dir / "_project"
        project_dir.mkdir(exist_ok=True)
        project_yaml = project_dir / "storage.yaml"
        project_yaml.write_text(
            "backend: notion\nnotion:\n  parent_page_id: abc123\n"
            "  databases:\n    backlog: db-1\n"
        )
        # Simulate rm -rf .briefcase (consumer reinstall)
        import shutil
        shutil.rmtree(consumer_dir / ".briefcase")

        result = run_install(consumer_dir)
        assert result.returncode == 0
        briefcase_yaml = consumer_dir / ".briefcase" / "storage.yaml"
        content = briefcase_yaml.read_text()
        assert "parent_page_id: abc123" in content
        assert "Syncing" in result.stdout or "canonical" in result.stdout

    def test_spaces_in_folder_name(self, tmp_path):
        """Bug fix: installer should handle spaces in project folder name."""
        target = tmp_path / "briefcase demo project"
        target.mkdir()
        result = run_install(target)
        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert (target / ".briefcase" / "src").is_dir()
        assert (target / "briefcase").exists()


class TestSafetyGuards:
    def test_self_install_guard_blocks_framework_repo_target(self):
        env = os.environ.copy()
        env["FRAMEWORK_DIR"] = FRAMEWORK_DIR
        env["TARGET_DIR"] = FRAMEWORK_DIR

        result = subprocess.run(
            ["bash", os.path.join(FRAMEWORK_DIR, "install.sh")],
            capture_output=True,
            text=True,
            env=env,
            timeout=30,
        )

        assert result.returncode != 0
        assert "framework into its own repo" in (result.stdout + result.stderr)
